config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :buckets do
     member do
      put "like", to: "buckets#upvote"
      put "dislike", to: "buckets#downvote"
    end
    resources :lists 
  end

  mount Commontator::Engine => '/commontator'
  

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :bucket
  acts_as_votable
  has_attached_file :image, styles: { large: "600x600",medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :list, except: [:index, :new, :create]
  before_action :bucket, except: [:index]

  def index	
  	@bucket = Bucket.find(params[:bucket_id]) 
  	@lists = @bucket.lists.paginate(:page => params[:page], :per_page => 6)
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = @bucket.lists.new(list_params)
    if @list.save
      flash[:success] = "New item has been added to the list."
      redirect_to bucket_list_path(@bucket, @list)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @list.update(list_params)
      flash[:success] = "List has been updated!"
      redirect_to bucket_list_path(@bucket, @list)
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    flash[:success] = "List has been destroy"
    redirect_to bucket_lists_path
  end
  
  private
      def list_params
        params.require(:list).permit(:title, :description, :completed, :image)
      end

      def list
        @list = List.find(params[:id])
      end

      def bucket
        # @bucket = current_user.buckets.find(params[:bucket_id])
        @bucket = Bucket.find(params[:bucket_id])
      end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<div class='row center'>
	<div class= 'container form-group'>
		<%= form_for [@bucket, @list],  html: { multipart: true } do |f| %>
	
		<div class='input-field'>
			<%= f.label :title %>
		  <%= f.text_field :title %>
		</div>
	
		<div class='input-field'>
		  <%= f.label :description %>
		  <%= f.text_area :description %>
		</div>
	
		<div class='input-field'>
		  <%= f.label :completed %>
		  <%= f.select :completed, [true, false], {}, class:"browser-default" %>
		</div>
	
		<div class='input-field'>
			<%= f.label :image %>
			<br /><br />
			<%= f.file_field :image %>
			<br /><br />
		</div>
		  <%= f.submit :class => 'btn' %>
		<%end%>
	</div>
</div>

app/views/lists/edit.html.erb
<h1>Edit List</h1>
<hr />

<%= render(partial: 'form') %>

app/views/lists/index.html.erb
<div class="container-fluid center">

  <h1><%= @bucket.title %></h1>

<% if @lists.any? %>
  <div class="row">
    <% @lists.each do |list| %>
    <div class="col s12 m4">
      <div class="card">
        <div class="card-image">
          <%= link_to (image_tag list.image.url(:medium)) %> <span class="card-title"><%= list.title %></span>
        </div>
        <div class="card-content">
          <p><%= list.description %></p>
        </div>
        <div class="card-action">
          <%= link_to 'More Info', bucket_list_path(id: list) %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
<% else %>
  <h3 class='center'>No Bucket list has been added!</h3>
<% end %>

<hr />
<%= link_to "Back to bucket", bucket_path(@bucket), class:'btn orange' %>
<% if @bucket.user_id == current_user.id %> 
  <%= link_to "Add to List", new_bucket_list_path(@bucket, @list), class:'btn green' %>
<% end %>

<%= will_paginate @lists, class:'paginate' %>

</div>

app/views/lists/new.html.erb
<h1>Enter New List</h1>
<hr />

<%= render(partial: 'form') %>

app/views/lists/show.html.erb
<div class="container-fluid center">

	<h1><%= @list.title%></h1>

	<div class="text-center">
		<%= image_tag @list.image.url(:large) %>
	</div>

	<h4><span><%= @list.description %></span></h4> <br/>

	<p><span>Completed:</span></p>
	<p><span><%= @list.completed %> </span> <br/></p>


	<% if @bucket.user_id == current_user.id %>
		<%= link_to "Edit list", edit_bucket_list_path(@bucket, @list),class:'btn orange' %> 
		<%= link_to "Delete", bucket_list_path(@bucket, @list) ,method: :delete, data: {confirm: 'Really delete?'}  ,class:'btn red' %> 
	<% end %> 
	<%= link_to "Back", bucket_lists_path(@bucket),class:'btn' %> 
</div>