config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :buckets do
     member do
      put "like", to: "buckets#upvote"
      put "dislike", to: "buckets#downvote"
    end
    resources :lists 
  end

  mount Commontator::Engine => '/commontator'
  

end

app/models/bucket.rb
class Bucket < ActiveRecord::Base
	acts_as_votable
	acts_as_commontable
	
  belongs_to :user
  has_many :lists, dependent: :destroy
  
  has_attached_file :image, styles: { large: "600x600", medium: "300x300#", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def self.search(search)
		  if search
		  	where("title LIKE ?" , "#{search}")
		 end
	end


	def self.by_title
		order(:title)
	end

	def self.by_description(high = false)
		if high
      order(description: :desc)
    else
      order(:description)
    end
	end 

	def self.by_completed
		order(:completed)
	end 









end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController

  before_action :bucket, except: [:index, :new, :create]

  def index
  	@buckets = current_user.buckets.paginate(:page => params[:page], :per_page => 6)
  end

  def show
    commontator_thread_show(@bucket)
  end

  def new
  	@bucket = Bucket.new
  end

  def create
  	@bucket = Bucket.new(bucket_params)
  	if @bucket.save
  		flash[:success] = "Bucket List Created."
  		redirect_to buckets_path
  	else
  		flash[:notice] = "Failed to create"
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @bucket.update(bucket_params)
  		flash[:success] = "Update completed"
  		redirect_to bucket_path
  	else
  		flash[:notice] = "Failed to update bucket list."
  		render :edit
  	end
  end

  def destroy
  	@bucket.destroy
    flash[:success] = "Deleted Bucket List."
  	redirect_to buckets_path
  end

  def upvote 
    @bucket.upvote_by current_user
    flash[:success] = "Upvoted Bucket List!"
    redirect_to :back
  end  

  def downvote
    @bucket.downvote_by current_user
    flash[:success] = "Downvoted Bucket List."
    redirect_to :back
  end

  private

  	def bucket_params
  		params.require(:bucket).permit(:title, :description, :completed, :user_id, :image)

  	end

  	def bucket
  		@bucket = Bucket.find(params[:id])
  	end
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/views/buckets/_form.html.erb
<div class='row center'>
  <div class='container form-group'>
    <%= form_for @bucket,  html: { multipart: true } do |f| %>

    <div class='input-field'>
      <%= f.label :title%>
      <%= f.text_field :title %>
    </div>

    <div class='input-field'>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>

    <div class='input-field'>
      <%= f.label :completed? %>
      <%= f.select :completed, [true, false], {}, class:"browser-default" %>
    </div>

    <div class='input-field'>
    	<%= f.label :image %>
      <br /><br />
    	<%= f.file_field :image %>
    </div>

    <div class='input-field'>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.submit :class => 'btn blue' %>
    </div>

    <%end%>
  </div>
</div>

app/views/buckets/edit.html.erb
<h1>Edit Bucket: </h1>

<%= render(partial: 'form') %>

<%= link_to "Back", buckets_path, class:'btn btn-danger' %> 

app/views/buckets/index.html.erb
<div class='center'>
<h1>Your Bucket Lists</h1>
<hr/>

<% if @buckets.any? %>
  <div class="row">
		<% @buckets.each do |bucket| %>
    <div class="col s12 m4">
      <div class="card">
        <div class="card-image">
       		<%= link_to (image_tag bucket.image.url(:medium)), bucket_path(bucket) %>           
          <span class="card-title"><%= bucket.title %></span>
        </div>
        <div class="card-content">
          <p><%= bucket.description %></p>
        </div>
        <div class="card-action">
          <%= link_to 'More Info', bucket_path(bucket) %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
<% else %>
	<h3 class='center'>No Bucket list, please add one!</h3>
<% end %>

<%= link_to "Add", new_bucket_path, class:'btn-floating btn-large waves-effect waves-light blue' %> 

<%= will_paginate @buckets, class:'paginate' %>

</div>

app/views/buckets/new.html.erb
<h1 class='center'>Creating New Bucket List</h1>

<%= render(partial: 'form') %>

<%= link_to "Back", buckets_path,class:'btn orange' %> 

app/views/buckets/show.html.erb
<div class="container-fluid center">
	<h1>Bucket Title: <%= @bucket.title %> </h1>


	<div class="text-center">
		<%= image_tag @bucket.image.url(:large) %>
	</div>

		<h4><span><%= @bucket.description %> </span> <br/></h4>
		<br />
		<p><span>Completed:</span></p>
		<p><span><%= @bucket.completed %></span> <br/></p>

	<%= link_to "List", bucket_lists_path(@bucket), class:'btn btn-success' %>
	<hr/>
	<div class='comments'>
		<%= commontator_thread(@bucket) %>
	</div>

	<% if @bucket.user_id == current_user.id %>
		<%= link_to "Edit Bucket", edit_bucket_path(@bucket), class:'btn orange'  %> 
		<%= link_to "Delete Bucket", bucket_path(@bucket), method: :delete, data: {confirm: 'Really Delete?'}, class:'btn red'  %> 
		<%= link_to "#{@bucket.user.email}'s Bucket", buckets_path, class:'btn green'  %>

	<% end %> 

	<%= link_to like_bucket_path(@bucket), method: :put, class:'btn glyphicon glyphicon-heart blue' do %>
	  <%= @bucket.get_upvotes.size %>
	<% end %>

	<%= link_to dislike_bucket_path(@bucket), method: :put, class:'btn glyphicon glyphicon-heart-empty red' do %>
	  <%= @bucket.get_downvotes.size %>
	<% end %>


</div>