config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :buckets do
     member do
      put "like", to: "buckets#upvote"
      put "dislike", to: "buckets#downvote"
    end
    resources :lists 
  end

  mount Commontator::Engine => '/commontator'
  

end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">DevPoint Labs Bucket List</h5>
        <p class="grey-text text-lighten-4">Thank you for using this app!</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Main Pages</h5>
        <ul>
          <li><%= link_to "Your Bucket", buckets_path, class:"grey-text text-lighten-3" %></li>
          <li><%= link_to "Explore", root_path, class:'grey-text text-lighten-3' %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2016 No Copyright Use 
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
  <li class="divider"></li>
  <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
</ul>
<nav>
  <div class="nav-wrapper">
    <%= link_to "Your Bucket", buckets_path, class:'navbar-brand' %>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to "Explore", root_path, class:'navbar-brand' %></li>
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><i class="material-icons right">Profile</i></a></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BucketList</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render(partial: 'layouts/navbar') %>

<% if flash.any? %>
	<% flash.each do |key, value| %>
		<div class="flash <%= key %>">
			<%= value %>
		</div>
	<% end %>
<% end %>

<%= yield %>

<%= render(partial: 'layouts/footer') %>

</body>
</html>